### ISSUE TITLE
Enabling by store doesn't work

### ISSUE THREAD

**Issue by alexmtch** [hyva-themes/magento2-hyva-checkout#29] opened 2021-04-29 09:50 UTC
# Env
- Magento EE 2.4
- magento2-hyva-checkout latest

# Step to reproduce
- Create 2 different store views
- Set the "hyva_checkout/general/enable" configuration for only one store
- Go to the checkout

# Expectations
Access to the checkout process

# Obtentions
This message :
```
No Checkout module installed.
Either install the Luma Fallback Checkout, or the React Checkout.
Please refer to the documentation for more information.
```

# Resolution
In vendor/hyva-themes/magento2-hyva-checkout/src/Config/Checkout.php
The "isEnabled" method should retrieve the flag by store.

**Comment by progammer-rkt** [comment] 2021-05-04 05:42
@alexmtch Thanks for reporting the issue. This will be soon looked into

**Comment by progammer-rkt** [comment] 2021-05-05 14:10
Hi @alexmtch , I could not reproduce this issue. Which branch did you use? I recommend using the `develop` branch for your work as it contains the major revamp of this module

**Comment by alexmtch** [comment] 2021-05-05 14:46
Hello, @progammer-rkt i tested on master and develop. As you can see in `Hyva\Checkout\Config\Checkout`,

![image](https://user-images.githubusercontent.com/14349499/117160325-4e5dde00-adc1-11eb-9067-a8cb72e428ce.png)

Should be

![image](https://user-images.githubusercontent.com/14349499/117160437-66356200-adc1-11eb-8959-3ea99a05e4bc.png)

**Comment by progammer-rkt** [comment] 2021-05-05 17:56
Ah.. now makes sense. Thank you. Pull requested created for this: #37 

Soon will be available in the `develop` branch 

Thanks again for the quick response 👍

**Comment by progammer-rkt** [comment] 2021-05-06 04:48
Closing this issue as the fix reached `develop` branch.

**Closed by progammer-rkt** 2021-05-06 04:48 UTC
Labels: bug
