### ISSUE TITLE
unclear and missing docs, two different node_modules folders

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-hyva-checkout#127] opened 2021-08-06 13:36 UTC
Does the develop branch work? Because for me it doesn't.

`npm start` fails with the following error:

```
npx postcss tailwind-source.css -o tailwind-output.css

npx: Installierte 4 in 1.333s
Programm konnte nicht gefunden werden: postcss
```

You may want to add the postcss-cli to the devDependencies.

`npm i postcss-cli --save-dev`

https://www.npmjs.com/package/postcss-cli

And also `postcss` in general:

```
npx postcss tailwind-source.css -o tailwind-output.css                                                                                                
Please install PostCSS 8 or above
```

`npm i postcss --save-dev`

**Comment by DanielRuf** [comment] 2021-08-06 13:48
One more candidate when running `npm start`:

```
Error: Cannot find module 'postcss-import'
```

**Comment by DanielRuf** [comment] 2021-08-06 13:58
Ok, it seems the docs are just very outdated which is making things harder then they should be =(

Two different node_modules folders can also lead to other issues in a project.

It seems we have to install things at `vendor/hyva-themes/magento2-hyva-checkout/src/view/frontend/web/css/tailwind` too.

**Comment by progammer-rkt** [comment] 2021-08-11 12:40
Closing this as it is a duplicate of #103

**Closed by progammer-rkt** 2021-08-11 12:40 UTC
